export const langs = `-Afrikaans-, -Albanian-, -Amharic-, -Arabic-, -Armenian-, -Azerbaijani-, -Basque-,

  -Belarusian-, -Bengali-, -Bosnian-, -Bulgarian-, -Catalan-, -Cebuano-, -Chichewa-,

  -Corsican-, -Croatian-, -Czech-, -Danish-, -Dutch-, -English-, -Esperanto-, -Estonian-,

  -Filipino-, -Finnish-, -French-, -Frisian-, -Galician-, -Georgian-, -German-, -Greek-,

  -Gujarati-, -Hausa-, -Hawaiian-, -Hebrew-, -Hebrew-, -Hindi-,

  -Hmong-, -Hungarian-, -Icelandic-, -Igbo-, -Indonesian-, -Irish-, -Italian-,

  -Japanese-, -Javanese-, -Kannada-, -Kazakh-, -Khmer-, -Korean-, -Kurdish-,

  -Kyrgyz-, -Lao-, -Latin-, -Latvian-, -Lithuanian-, -Luxembourgish-, -Macedonian-,

  -Malagasy-, -Malay-, -Malayalam-, -Maltese-, -Maori-, -Marathi-, -Mongolian-,

  -Myanmar-, -Nepali-, -Norwegian-, -Pashto-, -Persian-, -Polish-,

  -Portuguese-, -Punjabi-, -Romanian-, -Russian-, -Samoan-, -Serbian-,

  -Sesotho-, -Shona-, -Sindhi-, -Sinhala-, -Slovak-, -Slovenian-, -Somali-,

  -Spanish-, -Sundanese-, -Swahili-, -Swedish-, -Tajik-, -Tamil-, -Telugu-,

  -Thai-, -Turkish-, -Ukrainian-, -Urdu-, -Uzbek-, -Vietnamese-, -Welsh-,

  -Xhosa-, -Yiddish-, -Yoruba-, -Zulu-
`.replace(/-/g, '`');

export const langsObj = {
  af: 'Afrikaans',
  sq: 'Albanian',
  am: 'Amharic',
  ar: 'Arabic',
  hy: 'Armenian',
  az: 'Azerbaijani',
  eu: 'Basque',
  be: 'Belarusian',
  bn: 'Bengali',
  bs: 'Bosnian',
  bg: 'Bulgarian',
  ca: 'Catalan',
  ceb: 'Cebuano',
  ny: 'Chichewa',
  co: 'Corsican',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  nl: 'Dutch',
  en: 'English',
  eo: 'Esperanto',
  et: 'Estonian',
  tl: 'Filipino',
  fi: 'Finnish',
  fr: 'French',
  fy: 'Frisian',
  gl: 'Galician',
  ka: 'Georgian',
  de: 'German',
  el: 'Greek',
  gu: 'Gujarati',
  ha: 'Hausa',
  haw: 'Hawaiian',
  he: 'Hebrew',
  iw: 'Hebrew',
  hi: 'Hindi',
  hmn: 'Hmong',
  hu: 'Hungarian',
  is: 'Icelandic',
  ig: 'Igbo',
  id: 'Indonesian',
  ga: 'Irish',
  it: 'Italian',
  ja: 'Japanese',
  jw: 'Javanese',
  kn: 'Kannada',
  kk: 'Kazakh',
  km: 'Khmer',
  ko: 'Korean',
  ku: 'Kurdish',
  ky: 'Kyrgyz',
  lo: 'Lao',
  la: 'Latin',
  lv: 'Latvian',
  lt: 'Lithuanian',
  lb: 'Luxembourgish',
  mk: 'Macedonian',
  mg: 'Malagasy',
  ms: 'Malay',
  ml: 'Malayalam',
  mt: 'Maltese',
  mi: 'Maori',
  mr: 'Marathi',
  mn: 'Mongolian',
  my: 'Myanmar',
  ne: 'Nepali',
  no: 'Norwegian',
  ps: 'Pashto',
  fa: 'Persian',
  pl: 'Polish',
  pt: 'Portuguese',
  pa: 'Punjabi',
  ro: 'Romanian',
  ru: 'Russian',
  sm: 'Samoan',
  sr: 'Serbian',
  st: 'Sesotho',
  sn: 'Shona',
  sd: 'Sindhi',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  so: 'Somali',
  es: 'Spanish',
  su: 'Sundanese',
  sw: 'Swahili',
  sv: 'Swedish',
  tg: 'Tajik',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  cy: 'Welsh',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zu: 'Zulu',
};

const capitalize = str => str.charAt(0).toUpperCase() + str.slice(1);

export const getkey = key => {
  return Object.keys(langsObj).find(k => langsObj[k] === capitalize(key));
};
